### ISSUE TITLE
Yo como administrador debería poder crear usuarios y propiedades

### ISSUE THREAD

**Issue by AndreaPinonRattia** [ElVaquilla/FrontEndInmoworld#2]

**Comment by ElVaquilla** [comment]
Dado que estoy visualizando la lista de usuarios o propiedades.
Cuando pulso el botón de crear en cada lista se abre un formulario para poder rellenar toda la información necesaria. 
Entonces al finalizar el formulario aparece el nuevo usuario o propiedad en la lista.
