### ISSUE TITLE
Yo como usuario, al eliminar mi cuenta, veo un mensaje sobre la conservación de mis datos

### ISSUE THREAD

**Issue by AndreaPinonRattia** [ElVaquilla/FrontEndInmoworld#8]

**Comment by ElVaquilla** [comment]
Dado que estoy autenticado y estoy en mi perfil visualizando mi información personal
Cuando pulso el botón "Eliminar cuenta"
Entonces debería ver un modal con el mensaje "¿Estás seguro de que deseas eliminar tu cuenta?"
Y debajo del mensaje debería visualizar una notificación que indica "Tus datos serán conservados por 30 días antes de ser eliminados permanentemente"
Y el modal debería tener las opciones "Aceptar" y "Cancelar"
Cuando pulso "Aceptar"
Entonces mi cuenta debería eliminarse de la lista de usuarios
Y debería ser redirigido a la página de inicio con un mensaje de confirmación de eliminación de cuenta
