### ISSUE TITLE
Yo como usuario ya autenticado quiero eliminar mi cuenta

### ISSUE THREAD

**Issue by AndreaPinonRattia** [ElVaquilla/FrontEndInmoworld#9]

**Comment by ElVaquilla** [comment]
Dado que estoy autenticado y estoy en mi perfil visualizando mi información personal, como mi nombre, mi email y mis propiedades.
Cuando pulso el botón "Eliminar cuenta".
Entonces visualizo un modal en el que leo el mensaje "¿Estás seguro de que deseas eliminar a nombre del usuario?" y pulso aceptar eliminándolo de la lista de usuarios, teniendo la opción de cancelar también. 
Y debería ser redirigido a la página de inicio con un mensaje de confirmación de eliminación de cuenta.
